kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
